### ISSUE TITLE
Lost 2 lines of my fastq file when reverse complementing the file

### ISSUE THREAD

**Issue by senaj** [lh3/seqtk#104]
command:
seqtk seq -r forward.fq > rc_forward.fq

Line count of the input and output files

wc -l *fq

63008 forward.fq
63006 rc_forward.fq

**Comment by shenwei356** [comment]
You may upload some reads to reproduce the result.

**Comment by lh3** [comment]
Yes, it would be good to upload an example. You may first try unix command "tail" on both files to check if the last record is correct.

**Comment by lh3** [comment]
Close due to lack of information. Please reopen when have more information.
