### ISSUE TITLE
seqtk sample in for loop

### ISSUE THREAD

**Issue by SimonMorvan** [lh3/seqtk#112]
Hello,
I'm trying to subsample my fastq files with the seqtk sample function.
My files are named SF_Sx_R1.fastq and  SF_Sx_R2.fastq, x being a number. 
I've tried this loop:
_for i in {1..10} ; 
do
  ./seqtk sample -s100 SF_S$i_R1.fastq  25 > R1_sub$i.fastq ;
 ./seqtk sample -s100 SF_S$i_R2.fastq  25 > R2_sub$i.fastq ; 
done_
but it only creates empty fastq files. However, when I do
 _./seqtk sample -s100 SF_S1_R1.fastq  25 > R1_sub1.fastq_ it works fine...

What am I doing wrong?

**Comment by shenwei356** [comment]
seqtk sample -s100 SF_S${i}_R1.fastq 25 > R1_sub$i.fastq ;

**Comment by tseemann** [comment]
@SimonMorvan can you close this issue please?

**Comment by SimonMorvan** [comment]
yes!
