### ISSUE TITLE
New version release?

### ISSUE THREAD

**Issue by jpuritz** [lh3/seqtk#115]
Could the current master branch be released for bioconda compatibility?  Thanks!

**Comment by bgruening** [comment]
@lh3 we would need this in Bioconda for downstream projects that are using seqtk.
Thanks.

**Comment by tseemann** [comment]
@bgruening @jpuritz  Join the other 15 of us waiting over here: https://github.com/lh3/seqtk/issues/106
😆

**Comment by lh3** [comment]
Done. Thanks for pushing :-)

**Comment by bgruening** [comment]
Thanks @lh3!

**Comment by jpuritz** [comment]
Thank you @lh3!
