### ISSUE TITLE
Feature request: seqtk seq: multiline to single line Fasta

### ISSUE THREAD

**Issue by oschwengers** [lh3/seqtk#119]
Hi,
thanks for the great tool! I use it regularly and have incorporated it into many pipelines and workflows.

What do you thinks about a new `seqtk seq` option in order to wrap multi line fasta files into single line files?

Example:
```
>foo
atcgactgatg
ctagtcatgctg
gat
>bar
tagctacgttac
gattcga
```

would become:
```
>foo
atcgactgatgctagtcatgctggat
>bar
tagctacgttacgattcga
```

I do this very often to preprocess and filter huge fasta files. I guess this would be a nice feature for many people and implementing it shouldn't be a tough task...
Thanks a lot!

**Comment by shenwei356** [comment]
You need to update `seqtk`. `seqtk seq` outputs single line from at least 2 years ago.

**Comment by oschwengers** [comment]
Hello @shenwei356 ,
my fault....  thanks for the advice!
