### ISSUE TITLE
warning installing seqtk

### ISSUE THREAD

**Issue by andrewSharo** [lh3/seqtk#120]
While running make, I received the following warning that prevented installation:
andrewsharo@grand:~/bin/seqtk$ make
gcc -g -Wall -O2 -Wno-unused-function seqtk.c -o seqtk -lz -lm
seqtk.c: In function ‘stk_comp’:
seqtk.c:399:16: warning: variable ‘lc’ set but not used [-Wunused-but-set-variable]
    int la, lb, lc, na, nb, nc, cnt[11];
                ^
Would love to use this program, How can I get around this?

**Comment by lh3** [comment]
> warning that prevented installation:

Ignore warnings. They don't matter.

**Comment by xiaohongniua** [comment]
same question
and when type seqtk,I got 

Command 'seqtk' not found, but can be installed with:

sudo apt install seqtk
