### ISSUE TITLE
Trouble installing seqtk

### ISSUE THREAD

**Issue by jullee** [lh3/seqtk#122]
I've followed the instructions to download seqtk but when I type "make", I'm getting this error:

gcc -g -Wall -O2 -Wno-unused-function seqtk.c -o seqtk -lz -lm
/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/cc1: error while loading shared libraries: libmpfr.so.1: cannot open shared object file: No such file or directory
make: *** [seqtk] Error 1

I don't know how to proceed or what libmpfr.so.1 is...

**Comment by lh3** [comment]
That is your gcc problem. It will fail to install any programs.
