### ISSUE TITLE
seq -A identifies ">" in FASTQ as FASTA header

### ISSUE THREAD

**Issue by ZeweiSong** [lh3/seqtk#124]
It seems that the ">" character in the Q-score is mis-identified as the FASTA header when using the seq -A option:
```txt
>V300010089L2C001R004734960/2
ATGCGAGAACCAAGAGATCCGTTG
>:EFFFE>FFFFFFFFFGBFFFFFFFE;F@>+FF

>V300010089L2C001R004749445/2
ATGCGAGAACCAAGAG
```

**Comment by lh3** [comment]
But yours is not a fastq.

**Comment by ZeweiSong** [comment]
This is the FASTA output of "seq -A"

**Comment by lh3** [comment]
What matters is your FASTQ input.

**Comment by ZeweiSong** [comment]
Got it! My output from fastp has misplaced lines (for some reason).
