### ISSUE TITLE
subseq -t

### ISSUE THREAD

**Issue by MrLocuace** [lh3/seqtk#128]
Hello, I got a script which contains "seqtk subseq -t". I am not able to find what "-t" means. Thank you very much

**Comment by yzhernand** [comment]
The `-t` option for `seqtk subseq` tells seqtk to produce TAB delimited output. Run `seqtk subseq` and you will get the following message, which explains the options available for that command:

```
Usage:   seqtk subseq [options] <in.fa> <in.bed>|<name.list>

Options: -t       TAB delimited output
         -l INT   sequence line length [0]

Note: Use 'samtools faidx' if only a few regions are intended.
```

In general, you can run `seqtk COMMAND` without any other options to get a help dialog.

**Comment by yzhernand** [comment]
No problem. You should close the issue if you think it is resolved.
