### ISSUE TITLE
Sample Command Doesn't Work With Process Substitution

### ISSUE THREAD

**Issue by DarioS** [lh3/seqtk#135]
Using `<(zcat fastq.gz)` as input produces empty output. All of the examples use plain FASTQ files, which made me think it doesn't work with compressed ones. But, it does. The documentation could be much improved.

**Comment by lh3** [comment]
The second sentence in Introduction:

> It seamlessly parses both FASTA and FASTQ files which can also be optionally compressed by gzip.

2-pass sampling of course won't work with stream.
