### ISSUE TITLE
what does the meanning of '-Wno-unused-function' ?

### ISSUE THREAD

**Issue by lidd77** [lh3/seqtk#137]
HI, Heng,
I found this parameter name '-Wno-unused-function' when I checked the seqtk Makefile, but there is no any informatinon  about this on GCC help page via 'man gcc',  so what does '-Wno-unused-function'  ?     the right typing is '-Wunused-function' ？ 
BTW， the gcc version I use is 4.8 .

@lh3

**Comment by yzhernand** [comment]
Specific warnings can be turned on with an option like '-Wwarning-name' or off with '-Wno-warning-name' if gcc emits 'warning-name' warnings by default. In this case, prefixing 'unused-functions' with 'no-' turns off gcc warnings about unused functions. The 'no-' behavior is documented in the man page, but you won't find the exact name of the negated option if you search for it.

**Comment by lidd77** [comment]
Got it , thanks @yzhernand

**Comment by yzhernand** [comment]
@lidd77 if you consider this issue to be resolved, you should consider closing it
