### ISSUE TITLE
Failure to covert Fastq to fastA

### ISSUE THREAD

**Issue by orchid677** [lh3/seqtk#139]
Hi,

I've installed the tool but when I try your first command 

Beths-Air:seqtk Beth$ seq -a TT46_S643_L001_merged.fastq.gz > test.fasta

I get...

seq: illegal option -- a
usage: seq [-w] [-f format] [-s string] [-t string] [first [incr]] last

What am I missing?
Thanks.
Beth

**Comment by lh3** [comment]
```sh
seqtk seq -a
```

**Comment by orchid677** [comment]
Hmm.. I tried that but it says 

seqtk seq -a TT46_S643_L001_merged.fastq.gz > test.fasta
[E::stk_seq] failed to open the input file/stream.

I am in the correct directory and have set the path.
