### ISSUE TITLE
the size of file is different

### ISSUE THREAD

**Issue by Hulanyue** [lh3/seqtk#150]
Hi, @lh3 
I feel a little puzzled when I use `seqtk seq -l0 in.fq > out.fq` 

The size of file is different ,`in.fq:221.3MB , out.fq:217MB`

I don't think the file size will change normally，but I don't understand why it is different and Whether it  will influence the follow-up work  ,can you give me some advice?

**Comment by lh3** [comment]
Do a diff and you will see. Likely to be caused by fastq comments.
