### ISSUE TITLE
set seed with different samples

### ISSUE THREAD

**Issue by kaiwang12** [lh3/seqtk#154]
Hi,
I'm not sure how seqtk set up the seed. I have 20 samples, and each sample has 2 paired read files (forward and reverse). The smallest file only has 10,011 reads, the largest file has 50,032 reads. So I wanted to subsample all of my samples to this level (10,000). 

Do I have to change -s parameter for different samples, or should I use the same seed?

Thanks and any wisdom would be appreciated.

**Comment by lh3** [comment]
It doesn't matter. Either way works.
