### ISSUE TITLE
Seqtk sample ignores random seed

### ISSUE THREAD

**Issue by MatthewRalston** [lh3/seqtk#158]
Hello,
I'm experiencing a trouble recreating your example. I am certain this is not user error.
I have subsampled 10k reads as follows

```bash
>wc -l single_out.fq
2026312
>seqtk sample [-s $RANDOM] single_out.fq 10000 | wc -l
252
>seqtk sample [-s $RANDOM] single_out.fq 10000 | sha256sum
e279e6251a911ee24 ...
>seqtk sample [-s $RANDOM] single_out.fq 10000 | wc -l
252
>seqtk sample [-s $RANDOM] single_out.fq 10000 | sha256sum
e279e6251a911ee24 ...

#Also

>seqtk sample [-s $RANDOM] single_out.fq 1000 | wc -l
760
>seqtk sample [-s $RANDOM] single_out.fq 100000 | wc -l
760 # huh?
```

In contrast, setting my selection to 10000 in the following one-liners works fine. Not only is the correct number of reads produced (10000), but the data is fairly random according to the checksums.

http://userweb.eng.gla.ac.uk/umer.ijaz/bioinformatics/subsampling_reads.pdf

I've tried running `make clean` and re-`make`-ing, no difference. Checking out the latest release commit did not change the subsampling either.

**Comment by malonge** [comment]
Posting this in case it helps someone with a similar issue. I was using an unsigned 64-bit integer as the seed, but seqtk uses a signed 64-bit integer for the seed. As a result, I was exceeding the maximum allowable value with certain inputs. When the seed exceeds this limit, seqtk appears to default to the maximum possible seed value for a signed 64-bit integer, which is 9,223,372,036,854,775,807. This means that seeds larger than this will produce the same output, even if they seem distinct.

That said, I don't think this explains the original issue related to `$RANDOM`, as `$RANDOM` should not come anywhere near the maximum integer size. Still, anyone encountering my bug might find this post useful.
