### ISSUE TITLE
[feature] kmer counting

### ISSUE THREAD

**Issue by shouldsee** [lh3/seqtk#159]
Since seqtk is a fast toolkit, would it be possible to add some qc functionality?

**Comment by jelber2** [comment]
Perhaps you would like https://github.com/lh3/yak ?

**Comment by shouldsee** [comment]
> Perhaps you would like https://github.com/lh3/yak ?

Thanks for the pointer. Is it possible making `yak` a subcommand of `seqtk`?

**Comment by lh3** [comment]
Sorry. No.
