### ISSUE TITLE
could not ‘make’ in gcc 10.1.0 manjaro

### ISSUE THREAD

**Issue by shinepreventer** [lh3/seqtk#161]
make
gcc -g -Wall -O2 -Wno-unused-function seqtk.c -o seqtk -lz -lm
seqtk.c: 在函数‘stk_comp’中:
seqtk.c:400:16: 警告：变量‘lc’被设定但未被使用 [-Wunused-but-set-variable]
  400 |    int la, lb, lc, na, nb, nc, cnt[11];
      |                ^~
[wzy@wzy-pc seqtk]$ gcc --version
gcc (GCC) 10.1.0
Copyright © 2020 Free Software Foundation, Inc.

**Comment by lh3** [comment]
That is a warning, not an error.

**Comment by shinepreventer** [comment]
> That is a warning, not an error.

but I can not use seqtk after i make install because of this warning
