### ISSUE TITLE
Problems during installation

### ISSUE THREAD

**Issue by naurasd** [lh3/seqtk#166]
Hey guys,

got the following error during installation:

`$ cd seqtk; make
gcc -g -Wall -O2 -Wno-unused-function seqtk.c -o seqtk -lz -lm
process_begin: CreateProcess(NULL, gcc -g -Wall -O2 -Wno-unused-function seqtk.c -o seqtk -lz -lm, ...) failed.
make (e=2): The system cannot find the file.
make: *** [Makefile:8: seqtk] Error 2
`

Any idea what is going on here?

Cheers
Nauras

**Comment by yzhernand** [comment]
Just type in "make" in that directory. Drop everything from gcc and on.

**Comment by naurasd** [comment]
alright, cheers
