### ISSUE TITLE
output as compressed?

### ISSUE THREAD

**Issue by ahdee** [lh3/seqtk#173]
Hi I was wondering if its possible to output the files as compressed? 
I tried doing this. 

`seqtk subseq $fq1 names2.txt > strip2_R1.fq.gz`

but the resulting file is still ASCII based and not compressed. 

Thanks!

**Comment by lh3** [comment]
Please pipe to gzip.

**Comment by ahdee** [comment]
Thanks,  did'nt think about that until posting.
