### ISSUE TITLE
make warning

### ISSUE THREAD

**Issue by chenling-immunai** [lh3/seqtk#179]
Was installing on a ubuntu machine and ran into this warning. Not sure if this is relevant but just in case: 

```
gcc -g -Wall -O2 -Wno-unused-function seqtk.c -o seqtk -lz -lm
seqtk.c: In function ‘stk_comp’:
seqtk.c:461:16: warning: variable ‘lc’ set but not used [-Wunused-but-set-variable]
    int la, lb, lc, na, nb, nc, cnt[11];
                ^~

```

**Comment by KewinOgink** [comment]
Same issue, any solution?

**Comment by lh3** [comment]
Warnings are harmless.

> Just saw that seqtk is dead.

Who said it is dead? Rare changes mean seqtk is fairly stable.

**Comment by KewinOgink** [comment]
https://github.com/carpentries-incubator/hpc-intro/pull/213 

Maybe its just a warning and I have a different issue
![image](https://user-images.githubusercontent.com/46783201/135476025-6214adc9-1292-4695-9685-b79f958d8536.png)

**Comment by lh3** [comment]
You assembler doesn't work.
