### ISSUE TITLE
seqtk subseq in.fq name.lst > out.fq  didn't work 

### ISSUE THREAD

**Issue by li0604** [lh3/seqtk#180]
Hi everyone,

WHen I use the command  “seqtk subseq in.fq name.lst > out.fq”， there is no anything in the out.fq. The details showed as following:

other command line works. So I don't what's the reason about this problem.

Would you mind sharing your experience?

Thanks a lot.

**Comment by li0604** [comment]
![image](https://user-images.githubusercontent.com/54136123/126031704-71cd4331-e5ba-4c4c-8d66-8544f187ac0c.png)

**Comment by li0604** [comment]
![image](https://user-images.githubusercontent.com/54136123/126031755-08305059-feca-411d-b64a-a438b5ef355c.png)

**Comment by shenwei356** [comment]
cut -f 1 name.list > id.list

use id instead

**Comment by lh3** [comment]
As @shenwei356 said, you need to provide a list of names. `@` or `2:N:0:1` is not part of a name.
```
perl -ne 'print "$1\n" if /^@(\S+)/'
```

**Comment by li0604** [comment]
Thanks a lot. @lh3 @shenwei356
