### ISSUE TITLE
Seqtk trimfq used on files in .gz format returns much larger files but still .gz

### ISSUE THREAD

**Issue by bmillerlab** [lh3/seqtk#184]
I know that if seqtk program runs re-compression using a different gzip that changes in size may happen, but I'm getting differences like 436 Mb going to 2.2 Gb.  This does not seem correct.  I guess I am going to decompress and try re-compressing again using gunzip, but I wanted to check about this oddity.

Also a separate question, would it be hard to make it possible to run this using wildcards for file names or maybe input of an entire folder by calling the folder name and with output to a new folder?  

Thanks.

**Comment by lh3** [comment]
seqtk doesn't compress output. You need to pipe to gzip.
