### ISSUE TITLE
seqtk sample can't properly output fastq.gz

### ISSUE THREAD

**Issue by soappp9527** [lh3/seqtk#194]
I am trying to ramdomly extract 1000 reads from a fastq.gz
```
seqtk sample -s 999 all.fastq.gz 1000 > sub.fq.gz
```
but `sub.fq.gz` become readable just like a fastq text file which without gzip although with .gz suffix
```
$ gzip -l sub.fq.gz

gzip: sub.fq.gz: not in gzip format
``` 
seqtk sample seems can't gzip automatically

**Comment by lh3** [comment]
If you want gzip'd output, use pipe
```sh
seqtk sample -s 999 all.fastq.gz 1000 | gzip > sub.fq.gz
```
