### ISSUE TITLE
The output file size of seqtk subseq is zero

### ISSUE THREAD

**Issue by CherryX727** [lh3/seqtk#196]
Hi, when I use seqtk subseq, it runs normally and generates the specified output file without any error message.But the output file size is 0.The following is the code I used.
```seqtk subseq SRR8521657_R2_.fastq TTTTTTTGTCAN_sampleID.txt > TTTTTTTGTCAN.fastq```
How can I solve this problem?
Thanks for your answer.

**Comment by lh3** [comment]
Please make sure sequence names in .txt are present in the fastq.
