### ISSUE TITLE
Questions on telomere detection function

### ISSUE THREAD

**Issue by jetrz** [lh3/seqtk#218]
Hello, I have a question regarding the telomere detection functionality. 

How do I interpret the outputs in the .bed and .count files? For example, these are the outputs I receive;

telo.bed:
"
contig_1	0	3472	99573191
contig_1	99570322	99573191	99573191
contig_2	149096548	149100578	149100578
contig_3	230420914	230424412	230424412
contig_4	0	3145	102667201
contig_5	0	2041	296650268
contig_5	296647522	296650268	296650268
...
"

telo.count:
"
98072	3042286850
"

Thank you so much for your help on this! :-)

**Comment by jetrz** [comment]
Hello, to add on to this. Upon checking the regions in the .bed file, if I search for -m CCCATT, 

Let's say I get the result 
contig_1 0 3472 99573191
contig_1 99570322 99573191 99573191

The region from 0-3472 actually contains motif TTAGGG. Is this supposed to be the case? Help on this would be greatly appreciated!

**Comment by lh3** [comment]
You should see CCCATT on the 5'-end, not TTAGGG.
