### ISSUE TITLE
fastq file with empty sequences

### ISSUE THREAD

**Issue by lexnederbragt** [lh3/seqtk#3]
I am doing trimming/filtering using merTrim from Celera. This program does not remove sequences that it decides to delete from the input. Instead, it leaves an entry of length 0 in the fastq file. 'seqtk sample' stumbles upon these and reports a fasta header and one empty line for these in the fastq output. I can provide example data when needed.

**Comment by AlexBardill** [comment]
I'm still having this issue with the latest version of seqtk. After removing adapters with cutadapt, 0 length entries remain, which look like

```
@J00125:42:HCYCYBBXX:5:1106:2727:11530 2:N:0:TCCTGAGC+AGAGGATA

+

```

After using trimfq, this changes to
```
>J00125:42:HCYCYBBXX:5:1106:2727:11530 2:N:0:TCCTGAGC+AGAGGATA

```

**Comment by sjackman** [comment]
@AlexBardill  A workaround is to replace blank lines with a single `N`.
```sh
sed 's/^$/N/'
```

**Comment by lh3** [comment]
@AlexBardill and @lexnederbragt: see  32e7903

**Comment by sjackman** [comment]
Thanks, Heng.
