### ISSUE TITLE
Tag a recent stable release

### ISSUE THREAD

**Issue by sjackman** [lh3/seqtk#39]
Release 1.0 corresponds with r31, and the current commit of seqtk is r68. Please tag a recent stable release.

**Comment by tseemann** [comment]
Pretty please? :)

**Comment by Blahah** [comment]
Triple please :)

**Comment by sjackman** [comment]
With :cherries: on top?

**Comment by lh3** [comment]
Done. `v1.1` tag applied.

**Comment by sjackman** [comment]
Pull request to update Homebrew-science over here: https://github.com/Homebrew/homebrew-science/pull/3506
