### ISSUE TITLE
unsorted output when using seqtk subseq

### ISSUE THREAD

**Issue by peterdfields** [lh3/seqtk#49]
Is there a way to keep the subsetted sequences of say an extracted fasta file in the same order as the .lst file rather than sorting happen? For example I have contigs00xx and scaffolds00xx, and so even though contig and scaffold identifiers are interspersed throughout the .lst file, the final resulting fasta always has contigs first (essentially alpha numeric sorting). The issue arises as I'm trying to concatenate chunks of the draft assembly into linkage groups for downstream pop gen analysis. I've found alternatives using perl but generally find seqtk much much faster.

**Comment by lh3** [comment]
Unfortunately, due to the way subseq is implemented, it cannot keep the order in the intput. We would need a new implementation of subseq,
