### ISSUE TITLE
Not an issue... Permission to add seqtk to Archlinux User Repositories?

### ISSUE THREAD

**Issue by cyrilcros** [lh3/seqtk#50]
Hi,
with your permission I would like to add this software to the Archlinux distribution user repository (https://aur.archlinux.org/packages/seqtk-git). It means Archlinux users will be able to install your software seamlessly and have it updated when you make commits.
I assumed that this software is distributed under GPL license (from your other Github contributions), but I have not found any paper presenting it- if you want to be cited, please tell me how. I have made sure to mention Heng Li as the author.
If instead you would like me to take this Archlinux package down, I will do it at once (answer here or email me at cyril.cros@polytechnique.org).
Thanks again for your great work!
Cyril

**Comment by lh3** [comment]
Thank you for letting me know. It is great that you have ported the repo to Archlinux. A minor correction: the license is MIT, as is shown in most source code. You are right that this tool is unpublished.
