### ISSUE TITLE
A question ： about  fastq  quality encode 

### ISSUE THREAD

**Issue by WinterLi1993** [lh3/seqtk#65]
Hi ,teacher ,
    when I  use GATK  to treat my fastq reads ,  I meet such this error : SAM/BAM/CRAM file htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter@60b2082a appears to be using the wrong encoding for quality scores: we encountered an extremely high quality score of 62 

I search on the website ,I found somebody said  I can use Seqtk to fix such this misencoded quals , But I 
do not know how to do that ????
And why will appear such these misencoded quals in fastq reads ????

Expecting your answers !

**Comment by tseemann** [comment]
Has there been a mix-up between the old Illumina encoding and the new Sanger encoding?

See https://en.wikipedia.org/wiki/FASTQ_format#Encoding
