### ISSUE TITLE
A bug about seqtk 

### ISSUE THREAD

**Issue by WinterLi1993** [lh3/seqtk#66]
Hi
  I use seqtk to  convert my fastq : seqtk   seq  -V -Q 64  $1.fq > $1.s.fq 
and Use fastqQc , but I meet  such this error :  
  "FATAL ERROR (file fastq_qc_stat.c line 80): quality (-1) not in [0, 45]"

What happend about seqtk ? Thank you !

**Comment by lh3** [comment]
Could you show the violating line before and after "-VQ64"?

**Comment by WinterLi1993** [comment]
I think If I convert to 64phred ,should not appear  "-29 quality" , but I use fastQc tell something  wrong happend on fastq phred.
seqtk seq -V -Q 64 $1.fq > $1.s.fq
seqtk seq -V -Q 64 $2.fq > $2.s.fq

"fastq_qc_stat  -a  $1.fq  $2.fq  -f R02_N -q 45 -Q 64 

Error Information：  “FATAL ERROR (file fastq_qc_stat.c line 80): quality (-29) not in [0, 45]”

seqtk is work ??

**Comment by lh3** [comment]
-VQ64 converts Q64 quality to Q33 quality, not the other way around.
