### ISSUE TITLE
subseq not using the strand information in bed

### ISSUE THREAD

**Issue by pengchy** [lh3/seqtk#69]
Hi,
seqtk is so powerful and helpful to my regular work.
One problem for subseq tool is that it does not using the strand information in the bed file. I have tested using the same position with different strand information with same returned results.

Best,
Pengcheng

**Comment by lh3** [comment]
Unfortunately, seqtk ignores the strand field of bed. Will consider in future.

**Comment by pengchy** [comment]
Ok, thank you!
