### ISSUE TITLE
Seq and qual on the same line

### ISSUE THREAD

**Issue by demis001** [lh3/seqtk#74]
It output the quality on the seq line and give the quality on the separate again. The quality next to the sequence should be removed to be a correct format. Any fix? version 1.1

seqtk trimfq  -b 17  -e 17  outdir/input/seqWithWallBarcodeCombined.fastq >out_trim.fastq

@HISEQ:111:IHHVDQKLL:1:1000:900:20000 1:N:0:CATATTG
GGCTTTTGAGGATACCCCGGTCTCCCAAATAAATACATTCATCTGTAAAGATCGGAAGAGCACACCATATGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaO
+
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaO
@HISEQ:111:OJWOAZKVB:1:1000:900:20000 1:N:0:CATATTG
GGCTTTTGAAGGCCAGGACTCGTTTGTACCCGTTGATGATAGAATGGGCGATCGGAAGAGCACACTATATTGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaO
+
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaO

**Comment by lh3** [comment]
It is a bug in 1.1. Please use the latest master branch. Thanks.
