### ISSUE TITLE
License

### ISSUE THREAD

**Issue by wwood** [lh3/seqtk#76]
Hi,

I'm attempting to package seqtk for the GNU Guix package manager, and the packaging patch is being rejected because of some licensing concerns in seqtk. Would it be possible to address them please?

* The copyright notice on kstring.h lacks copyright dates.
* The copyright dates in seqtk.c and LICENSE are incorrect
   ("20082-2012"). 

Thanks,
ben

**Comment by tseemann** [comment]
@wwood Ben - any chance you can make a pull request?  @lh3  tends to accept them if they are clean.

**Comment by lh3** [comment]
Done.

**Comment by wwood** [comment]
OK, I've submitted a package to the Guix mailing list and I imagine it will land in master soon.
http://lists.gnu.org/archive/html/guix-devel/2016-09/msg00744.html

Thanks for writing this useful tool and for being generally awesome.
