### ISSUE TITLE
subseq losing paired end info

### ISSUE THREAD

**Issue by freelancer84** [lh3/seqtk#80]
When using subseq, Illumina paired end ID in description part is lost.

Exemple:
original
@DE18INS655:75:C493PACXX:7:1101:10003:21403 1:N:0:ACAGTC
resulting in
@DE18INS655:75:C493PACXX:7:1101:10003:21403

**Comment by tseemann** [comment]
@freelancer84 this bug was fixed in a more recent version of `seqtk`  - I am using `Version: 1.2-r94` and it keeps the description part.

**Comment by lh3** [comment]
@tseemann, thanks!
