### ISSUE TITLE
fastq fasta generator

### ISSUE THREAD

**Issue by dridk** [lh3/seqtk#81]
It sounds useless, but it would be useful to make some test ! 
- Generate random fasta 
- Generate random fastq from a fasta file, and with error or snp ! 

https://github.com/lh3/wgsim do the same job

**Comment by tseemann** [comment]
@dridk can you make a pull request with an example test framework?

**Comment by lh3** [comment]
I would prefer leave this functionality to other tools. Wgsim may work, but it is a bit outdated, and is not the exactly the tool you want.

Anyway, thanks for the suggestion.
