### ISSUE TITLE
Citing seqtk

### ISSUE THREAD

**Issue by ShobanaSekar** [lh3/seqtk#89]
Hi,

I am trying to cite seqtk in my paper, do you have an existing format or would this below one suffice?

H. Li, Seqtk: a fast and lightweight tool for processing FASTA or FASTQ sequences, 2013.

Thanks,
Shobana

**Comment by shenwei356** [comment]
I once cited seqtk as "website". Reference managers have type of "website".

**Comment by lh3** [comment]
As @shenwei356 said, just cite the github link. Seqtk is not published in a peer-reviewed journal. Thanks for pinging.

**Comment by tolot27** [comment]
@lh3 Maybe you can create at least a [citable doi}(https://guides.github.com/activities/citable-code).

**Comment by tbrunetti** [comment]
Or github now supports a `CITATION.cff` file so users can easily cite it if you add this to the repo: https://academia.stackexchange.com/questions/14010/how-do-you-cite-a-github-repository
