### ISSUE TITLE
Trim to a specified length

### ISSUE THREAD

**Issue by sjackman** [lh3/seqtk#9]
I'd like to trim a bunch of variable length reads to a fixed length. I read the help page for `seqtk trimfq`, but didn't see what I was looking for. Could this feature please be added?

**Comment by lh3** [comment]
Implemented via 46cd37e ... after 3 years. Sorry.

**Comment by sjackman** [comment]
Thanks, Heng!

**Comment by sjackman** [comment]
Would you please tag a new stable release tagged either `1.1` or `87`?
