### ISSUE TITLE
Trimming paired end reads with seqtk

### ISSUE THREAD

**Issue by Divyagash** [lh3/seqtk#92]
I used seqtk trimfq to trim paired end fastq files separately. After trimming when I try to align it I get an error saying 
`Paired read names do not match`

Is there a way to trim paired end reads simultaneously?

**Comment by tseemann** [comment]
Trimming can result in one of a pair being completely removed. So you may not end up with pairs at the end. You need to use `dropse` to remove those.

Here's one workflow you can use:

```
seqtk mergepe R1 R2 | seqtk trimfq - | seqtk dropse > R12.trim
seqtk seq -1 R12.trim | gzip > R1.trim.gz
seqtk seq -2 R12.trim | gzip > R2.trim.gz
```

**Comment by tseemann** [comment]
@Divyagash can you close this issue please?
