### ISSUE TITLE
Seqtk seq fastq to assembled.fa

### ISSUE THREAD

**Issue by Gabriellavp** [lh3/seqtk#93]
Hello, I am trying to run the command:
for i in {1..36};

do

seqtk seq -a "$i"-trimmed.fastq > “$i".assembled.fa;

done;

However it doesn't seems it is working. Does someone can help me with that?

**Comment by shenwei356** [comment]
Please format your code and paste error message.

**Comment by Gabriellavp** [comment]
Hi Shenwei356, thanks for the reply

the command is: seqtk seq -a "$i"-trimmed.fastq > “$i".assembled.fa; 
and the "$i" means my samples (files) from 1 to 36.

No error message appears, but no new files are generated either.

I dont know what to do :(

**Comment by Gabriellavp** [comment]
Actually it generates the file ".assembled.fa" however with zero bytes

**Comment by shenwei356** [comment]
It should be `seqtk seq -A` not `-a`.

**Comment by Gabriellavp** [comment]
Sorry, but no change

**Comment by shenwei356** [comment]
Which version are your using?

And run `seqtk seq -h` to print help message.

And try to test the command on one file.

Also, run `ls -lh 1-trimmed.fastq` to check the input file.

**Comment by hliang** [comment]
Before the seqtk command, try using `ls` to check if variables/files are valid:
```
for i in {1..36};
do
echo i = $i
ls -l "$i"-trimmed.fastq
seqtk seq -a "$i"-trimmed.fastq > "$i".assembled.fa;
done;
```
BTW, doesn't seem to be an issue of seqtk.

**Comment by Gabriellavp** [comment]
Thank you very much

**Comment by lh3** [comment]
Thank you, @hliang and @shenwei356!
