### ISSUE TITLE
support fasta output with subseq

### ISSUE THREAD

**Issue by tolot27** [lh3/seqtk#98]
It would be great if the `subseq` command would support fasta output as the `seq` command does.

**Comment by tseemann** [comment]
@tolot27 that's a useful idea. the `subseq` outputs in the same format you give it, so you could do either
1. `seq -A in.fq | subseq - > out.fa`
or
2. `subseq in.fq | seqtk -A - > out.fa`

**Comment by lh3** [comment]
Thanks, @tseemann. Piping is the recommended way.
